### ISSUE TITLE
Incorrect Download Link for Ipopt

### ISSUE THREAD

**Issue by dolaameng** [udacity/CarND-MPC-Quizzes#1]
For Linux users who want to install Ipopt locally, It seems that the [download link](https://github.com/coin-or/Ipopt/releases/) provided in README.md doesn't work with `install_ipopt.sh`, as they don't have the "ThirdParty" folder provided. 

Instead,  the users should be suggested to download them from https://www.coin-or.org/download/source/Ipopt/

The same issue applies to [MPC project](https://github.com/udacity/CarND-MPC-Project)

**Comment by domluna** [comment]
@dolaameng added the links back. There was an issue where coin-or was down for a few days so I changed the link to the github one but I have both there now. Thanks for the issue!
