### ISSUE TITLE
cannot install ipopt on Mac

### ISSUE THREAD

**Issue by lb5160482** [udacity/CarND-MPC-Quizzes#15]
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb
Calling 'depends_on :mpi' is disabled!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb:35:in `<class:Mumps>'
Please report this to the udacity/carnd-mpc-project tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap udacity/carnd-mpc-project: invalid syntax in tap!

**Comment by mvirgo** [comment]
You might try `brew tap dpo/homebrew-openblas` and then re-try the install.

**Comment by lb5160482** [comment]
@mvirgo Thanks! I tried but still get the same error 
``Error: Invalid formula: /usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb
Calling 'depends_on :mpi' is disabled!
Use 'depends_on "open-mpi"' instead.
/usr/local/Homebrew/Library/Taps/udacity/homebrew-carnd-mpc-project/mumps.rb:35:in `<class:Mumps>'
Please report this to the udacity/carnd-mpc-project tap!
Or, even better, submit a PR to fix it!
Error: Cannot tap udacity/carnd-mpc-project: invalid syntax in tap!
``

when I run `brew tap udacity/CarND-MPC-Project https://github.com/udacity/CarND-MPC-Project`

**Comment by mvirgo** [comment]
That's because you are tapping the incorrect repository. You should not tap the udacity MPC repo at all; please use the one above and proceed accordingly.

**Comment by lb5160482** [comment]
Also this helps: [here](https://github.com/udacity/CarND-MPC-Project/issues/24#issuecomment-383520943)
