### ISSUE TITLE
Terminate with Error loading matplotlib.pyplot

### ISSUE THREAD

**Issue by Grillen80** [udacity/CarND-MPC-Quizzes#18]
It compiles without error and the simulation runs until it terminates with throwing an instance of 'std::runtime_error'
  what():  Error loading module matplotlib.pyplot!

matplotlib for python and python3 is already installed as suggested. 
Im working under Linux Mint 16.04 without the docker

**Comment by mvirgo** [comment]
[This StackOverflow post](https://stackoverflow.com/questions/21784641/installation-issue-with-matplotlib-python?noredirect=1&lq=1) has a fix for this (I actually suggest the comment under the primary solution mentioning "`import matplotlib as mpl` then `mpl.use('TkAgg')`.

Note that I originally got to this solution from the end of [this issue](https://github.com/lava/matplotlib-cpp/issues/8), in case you're wondering how I got there.

Closing based on age, but feel free to comment again if you are still having issues / focused on this quiz.

**Comment by RuslanSafronoff** [comment]
> It compiles without error and the simulation runs until it terminates with throwing an instance of 'std::runtime_error'
> what(): Error loading module matplotlib.pyplot!
> 
> matplotlib for python and python3 is already installed as suggested.
> Im working under Linux Mint 16.04 without the docker

How did you solve this problem?
