### ISSUE TITLE
install python dev for matplotlib header file

### ISSUE THREAD

**Issue by ranakhalil** [udacity/CarND-MPC-Quizzes#2]
To be able to access the Python header files, we need to have the python sources installed properly

On linux (debian and Ubuntu) and linux subsystems on windows it should look something like:

```
sudo apt-get install python-dev  # for python2.x installs

```

I recommend adding that to the README as part of a dependency needed to avoid it for students who might run into this issue.

For python 3.x dependencies you would do:
```
sudo apt-get install python3-dev  # for python3.x installs

```

Then to make sure matplotlib will work:

```
sudo apt-get install python-matplotlib
```
for python 3.x:

```
sudo apt-get install python3-matplotlib
```

**Comment by mvirgo** [comment]
Looks like @baumanab added this through fe16779, so closing out. Thank you for bringing this to our attention!
