### ISSUE TITLE
Add Conan package manager

### ISSUE THREAD

**Issue by Horki** [udacity/CarND-MPC-Quizzes#21]
Not an issue, but suggestion.
It would be nice to add [Conan](https://conan.io/) package manager for Eigen, the repo will look much cleaner.

example: https://github.com/Horki/CarND-MPC-Quizzes/blob/master/mpc_to_line/conanfile.txt

**Comment by UAnjali** [comment]
Hi @Horki,
Thanks for suggesting an update to the repo. We will look into this.
Happy Learning
Udacity

**Comment by Horki** [comment]
@UAnjali hahahaha
