### ISSUE TITLE
Code Comments

### ISSUE THREAD

**Issue by timtobey** [udacity/CarND-MPC-Quizzes#4]
First, thank you for putting these quizzes together for the MPC.

As you are probably aware, the students are not only trying to learn the lesson concept but a large number of the students are also so trying to learn the  C++ coding concepts as well

There are some items  and processes I don't understand.   I also dont think they are obvious to the  main stream student.   

For instance line 56 of the MPC.cpp:
 void operator()(ADvector& fg, const ADvector& vars)

It is unclear to me what this does, why it was used and how helps the process

Could you provide some detail please. I think it would be helpful.

In commenting your code, providing  insight to the rational behind the code process would be very helpful to a number of us lesser "geniuses" in the program.

Again, thanks for all your hard work here.

**Comment by domluna** [comment]
@timtobey You're absolutely right. Additional concepts are being made to explain the packages and code in more detail.

As to

```cpp
void operator()(ADvector& fg, const ADvector& vars) {
  ...
}
```

It's mainly for the Ipopt API. Ipopt requires an object that can be called which evaluates the cost, model constraints, variables, etc.

```cpp
// Object that computes objective and constraints
FG_eval fg_eval(coeffs);
```

```cpp
// solve the problem
CppAD::ipopt::solve<Dvector, FG_eval>(
    options, vars, vars_lowerbound, vars_upperbound, constraints_lowerbound,
    constraints_upperbound, fg_eval, solution);
```

`fg_eval` is then called several times during the optimization problem.

https://github.com/coin-or/CppAD/blob/master/cppad/ipopt/solve_callback.hpp#L164

Hope that clears things up a little.

**Comment by timtobey** [comment]
Thanks for the guidance, that was helpful.
